# Interactive component


```{r}
library(pacman)

pacman::p_load(plotly,quantmod)

APPLE_stock <- getSymbols("AAPL",auto.assign = F)
date <- index(APPLE_stock)

APPLE_df <- data.frame(APPLE_stock,row.names=NULL)
APPLE_df$Date <- date
colnames(APPLE_df) <- c("Open", "High", "Low", "Close", "Volume", "Adjusted", "Date")

APPLE_df <- APPLE_df%>%
  filter(Date>"2017-01-01")

head(APPLE_df)
```



We are interested in stock performance after Jan 2017

```{r}
barcols <- c()

for(i in 1:length(APPLE_df$Date)){
  if(i==1){
    barcols[i] <- "#F95959"
  }
  if(i>1){
    x <- ifelse(APPLE_df$Close[i] > APPLE_df$Close[i-1],"#455D7A", "#F95959")
    barcols[i] <- x
  }
}

Moving_average <- runMean(APPLE_df$Close)

rangeselectorlist = list(
  x = 0, y = 0.9,
  bgcolor = "#0099cc",
  font = list(color = "white"),
  
  buttons = list(
    list(count = 1, label = "reset", step = "all"),
    list(count = 1, label = "1yr", step = "year", stepmode = "backward"),
    list(count = 3, label = "3 mo", step = "month", stepmode = "backward"),
    list(count = 1, label = "1 mo", step = "month", stepmode = "backward"),
    list(step = "all")
  )
)

plot_ly(APPLE_df, type = "candlestick",
        x = ~Date,
        open = ~Open, high = ~High, low = ~Low, close = ~Close,
        yaxis = "y",
        increasing = list(line = list(color = "#455D7A")),
        decreasing = list(line = list(color = "#F95959")),
        name = "Price",
        height = 600, width = 1024) %>%
  
  add_bars(data = APPLE_df, x = ~Date, y = ~Volume,
           marker = list(color = barcols),
           yaxis = "y2", inherit = F, name = "Vol") %>%
  
  add_lines(x = APPLE_df$Date, y = Moving_average,
            line = list(width = 3, dash = "5px", color = "#33bbff"),
            inherit = F, name = "Mov Avg") %>%
  
  layout(
    plot_bgcolor = "rgb(250,250,250)",
    xaxis = list(title = "", domain = c(0,0.95),
                 
                 rangeslider = list(visible = F),
                 
                 rangeselector = rangeselectorlist),
    yaxis = list(domain = c(0.22, 0.9)),
    yaxis2 = list(domain = c(0, 0.18), side = "right"),
    
    showlegend = F,
    
    annotations = list(
      list(x = 0, y = 1, xanchor = "left", yanchor = "top",
           xref = "paper", yref = "paper",
           text = paste0("<b>APPLE</b>"),
           font = list(size = 30, family = "serif"),
           showarrow = FALSE),
      
      list(x = 0.8, y = 0.95, xanchor = "left", yanchor = "top",
           xref = "paper", yref = "paper",
           text = paste0("[", paste(range(APPLE_df$Date),collapse = " / "), "]"),
           font = list(size = 15, family = "serif"),
           showarrow = FALSE),
      
      list(x = 0, y = 0.18, xanchor = "left", yanchor = "top",
           xref = "paper", yref = "paper",
           text = paste0("<b>Volume</b>"),
           font = list(size = 15, family = "serif"),
           showarrow = FALSE)
    )
  )

```

Based on this interactive plot, the audience can see the change of moving average price and volumes traded for each day after 2017 clearly. Also, the audience can change the time period (1year/3month/1month/all) depending on their needs by clicking the button below the company name.


