# Conclusion



From the above graphical analysis of the US Stock market. We conclude that from a board perspective, S&P 500 does not have the highest returns overall and it is not hard to understand that since it included all sectors from the market, the returns will be hedged. Instead, the most high returns follow with continuously increasing returns is Technology Information Industry. But still, the general returns on S&P 500 give relatively high returns just behind Technology and Consumer Discretionary sectors. I would suggest that if a risk-preferring investor is pursuing high returns, investing in the index of technology and consumer discretionary sector would be a good choice or by vertical selection to select stocks inside those two industries. However, moderate investors who invest money in SP500 are still a good choice. This would not only give you a relatively high return but with a lower risk because it melts in all 11 sectors and each sector could hedge to the others.  Further, we learned that recent years starting from 1999 Technology indeed have had a boom in development. The including number of companies of Technology Sector increase a lot since 1999 and keep the most proportion in component of SP500 years to years. 

As we look in depth, we can conclude that the stocks in the same sector, like Apple & Google share a similar upward or downward trend. So to avoid the high risk, risk-averse investors would better invest the money in stocks in different sectors or stocks with lower correlations. Secondly, when we want to specifically invest in the whole industry, for within 5 years, Technology, Health Care, and Consumer Discretionary might still be a good choice. However, be cautious when investing in the Energy Sector unless you are an expert and have a huge confidence in this industry or you believe you are the “survivor” or “outlier” on investing in the Energy Sector. 

The limitations are mainly focused on we just have a broad overview. And the analysis above could just share some insights on the past 5 years returns and prefer industry to invest. However, There are many variations in the stock market and we are not able to ensure that investing in the sector that we recommend would earn profit 100% of the time. There are many other factors that would affect investment like government policies, warfare, business cycles. Also making profit in long terms not indicated and represented it could also earn high returns in the short term period. More fluctuations included for short term investors. Therefore, more in depth and specific exploration need to be done in order to have a thorough understanding of the stock market. But at least, the analysis above provides us some insights and could help us avoid stepping on some industries that are difficult to make money.