--- 
title: "USStock Market"
author: "Weilin Zhou & Xiaoyuan Ge"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

In the financial market, people(including individual and institutional investors) make money more easily under the bull market than in the bear market due to more companies raising their prices under the bull market environment. Following the flow of the market would always benefit investors. However, there are too many public companies in the stock market and how would we know if the market is going well or bad? Here, some indexes representing the market are good tools to provide insights for investors to tell them about the performance overall. S&P 500(Standard and Poor’s 500) is always one of the indexes that people use. 


By having a general knowledge of what is S&P 500, here is the official explanation of it: the S&P 500 Index features 500 leading U.S. publicly traded companies, with a primary emphasis on market capitalization. And it is not an exact list of the top 500 U.S. companies by market cap because there are other criteria that the index includes. And usually people, whether doing investment or doing business, would refer to the index of the whole market to make investment decisions. Therefore the S&P 500 index is a diversified basket of an entire market including each different sector in the market with the highest 500 market cap. Since there are different companies including different sectors in the SP500, we are curious on how each sector interacts with the whole financial market. And how they affect the whole market.	


This topic especially interested for both of the two of us is because we are financial-related backgrounds and in the daily life, we invest money in the stock market therefore the questions that interested us also would facilitate us with our daily investing and learn in depth would give us a more general overview.
